Use the fish shell
* Using `starship` for my prompt means that it behaves exactly as it did
  in Zsh, which is quite nice.
* Convert `zshrc` to `config.fish`
* Autoload most functions, except the ones that are called in
  `config.fish` and thus will always be used
* `fish_add_path` is neat!
* Writing completions will probably never be a joy, but Fish's system is
  certainly less painful than the one in Zsh. `-w 'git branch'` is so
  much nicer than `compdef _git gc=git-branch`.

diff --git a/bin/find-location-of b/bin/find-location-of
--- a/bin/find-location-of
+++ b/bin/find-location-of
@@ -1,4 +1,5 @@
-#!/usr/bin/env zsh
+#!/usr/bin/env fish
+# vim: syntax=fish
 
 # Finds a script file, shell alias, or shell function and prints its
 # location, including a the line number. The line number is always included for
@@ -8,102 +9,79 @@
 # Usage:
 #
 #     $ find-location-of myalias
-#     ~/.zshrc:530
+#     /Users/gabe/.config/fish/config.fish:32
 #
 #     $ find-location-of git-merge-to
-#     ~/.bin/git-merge-to:1
+#     /Users/gabe/code/personal/dotfiles/tag-git/bin/git-merge-to:1
 #
-#     $ find-location-of which
-#     which is a shell builtin (printed to STDERR)
-#     exits 1
+#     $ find-location-of time
+#     time is a shell builtin
+#     [printed to STDERR]
+#     [exits 1]
 
-source ~/.zshrc
+set FISH_CONFIG_FILE ~/.config/fish/config.fish
+source $FISH_CONFIG_FILE
 
-_handle_unknown_command() {
-  echo "\"$1\" is not recognized as a script, function, or alias" >&2
-  echo "(searched in $(_search_paths))" >&2
+function handle_unknown_command -a cmd
+  echo "\"$cmd\" is not recognized as a script, function, or alias" >&2
   exit 1
-}
+end
 
-_follow_symlink(){
-  if [[ -L "$1" ]]; then
-    readlink "$1"
-  else
-    print "$1"
-  fi
-}
-
-_definition_type() {
-  arg_type_string=$(type -a "$1")
-  if [[ "$arg_type_string" == *"is an alias"* ]]; then
-    echo "alias"
-  elif [[ "$arg_type_string" == *"is a shell function"* ]]; then
-    echo "function"
-  elif [[ "$arg_type_string" == *"is a shell builtin"* ]]; then
+function definition_type -a cmd
+  switch (type -t $cmd)
+  case "function"
+    set -f typeinfo (type -a $cmd)
+    if string match -q -e -- "--description 'alias" $typeinfo
+      echo "alias"
+    else if string match -q -e -- "function with definition" $typeinfo
+      echo function
+    else
+      echo "not found"
+    end
+  case builtin
     echo "builtin"
-  elif [[ "$arg_type_string" == *"reserved word"* ]]; then
-    echo "builtin"
-  elif [[ "$arg_type_string" == *"is an autoload shell function"* ]]; then
-    # Can't edit these, but they do show up in `which`, so short-circuit here
-    echo "not found"
-  elif which "$1" > /dev/null 2>&1; then
+  case file
     echo "script"
-  else
+  case "*"
     echo "not found"
-  fi
-}
+  end
+end
 
-_edit_script() {
-  local script_path=$(_follow_symlink "$(which "$1")")
-  echo "$script_path":1
-}
+function find_script -a cmd
+  set -f script_path (realpath $(which $cmd))
+  echo $script_path:1
+end
 
-_definition_field_for_pattern() {
-  _grep_for_definition -n "$2" | cut -d ":" -f "$1"
-}
+function find_shell_function -a funcname
+  set -f typeinfo (type -a $funcname)
+  # "Defined in /Users/gabe/.config/fish/config.fish @ line 2"
+  string match -rq "Defined in (?P<filename>[^ ]+) @ line (?P<line_number>\d+)" $typeinfo
+  echo $filename:$line_number
+end
 
-_search_paths(){
-  echo ~/.zshrc ~/.zshenv ~/.aliases
-}
+function find_shell_alias -a funcname
+  rg --no-filename -n "alias $funcname " $FISH_CONFIG_FILE | string match -r -q -g '^(?P<line_number>\d+)'
+  # I know that all aliases are in $FISH_CONFIG_FILE
+  # There's no rule about it, I just know that I do that.
+  echo "$FISH_CONFIG_FILE:$line_number"
+end
 
-_grep_for_definition(){
-  grep -E "$@" $(_search_paths) 2>/dev/null
-}
-
-_edit_based_on_pattern(){
-  local pattern=$1
-  local command_name=$2
-
-  if _grep_for_definition -q "$pattern"; then
-    file=$(_definition_field_for_pattern 1 "$pattern")
-    line=$(_definition_field_for_pattern 2 "$pattern")
-    echo "$(_follow_symlink "$file")":"$line"
-  else
-    _handle_unknown_command "$command_name"
-  fi
-}
-
-_edit_shell_function() {
-  _edit_based_on_pattern "(^function $1[ {()])|(^$1\(\))" "$1"
-}
-
-_edit_shell_alias() {
-  _edit_based_on_pattern "alias $1=" "$1"
-}
-
-if [[ $# == 0 ]]; then
+if [ (count $argv) -eq 0 ]
   echo "No argument given" >&2
   exit 1
 else
-  command_name="$1"
-  case "$(_definition_type "$command_name")" in
-    "alias") _edit_shell_alias "$command_name";;
-    "function") _edit_shell_function "$command_name";;
-    "builtin")
+  set -l command_name $argv[1]
+  switch (definition_type $command_name)
+    case "alias"
+      find_shell_alias $command_name
+    case "function"
+      find_shell_function $command_name
+    case "builtin"
       echo "$command_name is a shell builtin" >&2
       exit 1
-    ;;
-    "script") _edit_script "$command_name";;
-    "not found") _handle_unknown_command "$command_name"
-  esac
-fi
+    case "script"
+      find_script $command_name
+    case "not found"
+      handle_unknown_command $command_name
+  end
+end
